#!/usr/bin/env node
/**
 * Reads ../openapi.json and writes ../postman.json (root of repo)
 * via openapi-to-postmanv2.
 *
 * Output is committed so QA / support folk can import the collection
 * straight from GitHub without re-running this script.
 *
 * The CI workflow .github/workflows/sdk-ts-drift.yml regenerates and
 * diffs against the committed file — keeps the collection in sync
 * with the spec.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import Converter from 'openapi-to-postmanv2';

const here = dirname(fileURLToPath(import.meta.url));
const specPath = resolve(here, '..', '..', 'openapi.json');
const outPath = resolve(here, '..', '..', 'postman.json');

const spec = await readFile(specPath, 'utf8');

const collection = await new Promise((resolveP, reject) => {
  Converter.convert(
    { type: 'string', data: spec },
    {
      // Keep the output deterministic: no random folder ids; sort
      // alphabetically. Without these the CI drift gate would
      // false-positive on every run.
      folderStrategy: 'Tags',
      keepImplicitHeaders: false,
      requestParametersResolution: 'Schema',
      exampleParametersResolution: 'Schema',
      includeAuthInfoInExample: false,
    },
    (err, result) => {
      if (err) {
        reject(err);

        return;
      }
      if (!result?.result) {
        reject(new Error(result?.reason ?? 'openapi-to-postmanv2 failed'));

        return;
      }
      resolveP(result.output[0].data);
    },
  );
});

// Sort the top-level item array by name so the output is stable
// across runs. The library doesn't guarantee insertion order across
// Node versions.
if (Array.isArray(collection.item)) {
  collection.item.sort((a, b) => (a.name ?? '').localeCompare(b.name ?? ''));
}

// Strip the volatile `_postman_id` (regenerated by Postman on import)
// — keeping it would also flap the drift gate.
delete collection.info?._postman_id;

await writeFile(outPath, JSON.stringify(collection, null, 2) + '\n', 'utf8');

console.log(`✓ Wrote ${outPath}`);
